version: "2"

output:
  formats:
    code-climate:
      path: stdout
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true

run:
  timeout: 10m
  modules-download-mode: "mod"
  tests: false
  issues-exit-code: 0

severity:
  # Use severity from: https://docs.codeclimate.com/docs/issues#issue-severity
  default: minor
  rules:
    - linters:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - gofumpt
      severity: critical

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - gofumpt
    - lll
    - prealloc
    - predeclared
    - gocheckcompilerdirectives
    - goprintffuncname
    - gosec
    - interfacebloat
    - nakedret
    - containedctx
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - mirror
    - nilerr
    - nilnil
    - perfsprint
    - protogetter
    - reassign
    - rowserrcheck
    - unconvert
    - wastedassign
  disable:
    - "unused"


  settings:
    staticcheck:
      checks: ["all"]            # Enable all staticcheck rules
    errcheck:
      check-type-assertions: true # Enable type assertion checks
      check-blank: false
    govet:
      enable:
        - shadow
    predeclared:
      qualified-name: true
    gosec:
      severity: high
      confidence: high
      includes:
        - G101
        - G109
        - G115
        - G201
        - G202
        - G203
        - G204
        - G303
        - G404
        - G501
        - G505
        - G601
        - G602
    interfacebloat:
      max: 7
    nakedret:
      max-func-lines: 30
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
    protogetter:
      skip-any-generated: true
    lll:
      line-length: 150
    wsl:
      strict-append: true
      allow-assign-and-anything: false
      allow-multiline-assign: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: false
      allow-separated-leading-comment: false
      force-err-cuddling: true
      error-variable-names: ['err']
      force-short-decl-cuddling: false
