import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Sidebar layout for the Lahijan docs site.
// Auto-generates from ../docs/ folder structure, with explicit category labels.

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "doc",
      id: "README",
      label: "Overview",
    },
    {
      type: "category",
      label: "Architecture",
      items: [
        { type: "autogenerated", dirName: "architecture" },
      ],
    },
    {
      type: "category",
      label: "Decisions (ADRs)",
      items: [
        { type: "doc", id: "adr/README", label: "Index" },
        { type: "autogenerated", dirName: "adr" },
      ],
    },
    {
      type: "category",
      label: "Workstreams",
      items: [
        { type: "doc", id: "workstreams/README", label: "Index" },
        { type: "autogenerated", dirName: "workstreams" },
      ],
    },
    {
      type: "doc",
      id: "glossary",
      label: "Glossary",
    },
  ],
};

export default sidebars;
