#!/bin/sh
# Generates the passwords and keys of a Lahijan install on first start.
#
# Writes /secrets/secrets.env once. Re-running does nothing, so the secrets
# survive restarts and upgrades; remove the volume only to start from scratch
# (that also means a new database, because the old password is gone).
#
# Every line has the form  : "${NAME:=value}"  which only assigns when NAME is
# empty, so anything set in .env takes precedence over a generated value.
set -eu

out=/secrets/secrets.env
if [ -s "$out" ]; then
	echo "secrets already generated"
	exit 0
fi

hex() { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }
b64() { head -c "$1" /dev/urandom | base64 | tr -d '\n'; }

tmp="$out.tmp"
{
	echo "# Generated by Lahijan on first start. Do not edit; set a value in .env to override one."
	for line in \
		"POSTGRES_PASSWORD=$(hex 24)" \
		"LAHIJAN_DB_PASSWORD=$(hex 24)" \
		"PDNS_DB_PASSWORD=$(hex 24)" \
		"SEAWEED_DB_PASSWORD=$(hex 24)" \
		"PDNS_API_KEY=$(hex 32)" \
		"SEAWEEDFS_S3_ACCESS_KEY=$(hex 16)" \
		"SEAWEEDFS_S3_SECRET_KEY=$(hex 32)" \
		"LAHIJAN_AUTH_SIGNING_KEY=$(b64 48)" \
		"LAHIJAN_AUTH_SECRETS_ENCRYPTIONKEY=$(b64 32)"; do
		name=${line%%=*}
		value=${line#*=}
		printf ': "${%s:=%s}"\nexport %s\n' "$name" "$value" "$name"
	done
	# The same secret under the names each program reads it by.
	cat <<'EOF'
: "${LAHIJAN_DATABASE_PASSWORD:=$LAHIJAN_DB_PASSWORD}"
export LAHIJAN_DATABASE_PASSWORD
: "${LAHIJAN_PROVIDERS_POWERDNS_APIKEY:=$PDNS_API_KEY}"
export LAHIJAN_PROVIDERS_POWERDNS_APIKEY
: "${LAHIJAN_PROVIDERS_SEAWEEDFS_ADMINACCESSKEY:=$SEAWEEDFS_S3_ACCESS_KEY}"
export LAHIJAN_PROVIDERS_SEAWEEDFS_ADMINACCESSKEY
: "${LAHIJAN_PROVIDERS_SEAWEEDFS_ADMINSECRETKEY:=$SEAWEEDFS_S3_SECRET_KEY}"
export LAHIJAN_PROVIDERS_SEAWEEDFS_ADMINSECRETKEY
: "${WEED_POSTGRES2_PASSWORD:=$SEAWEED_DB_PASSWORD}"
export WEED_POSTGRES2_PASSWORD
EOF
} >"$tmp"

# Readable by the non-root users some of the images run as.
chmod 644 "$tmp"
mv "$tmp" "$out"
echo "secrets generated"
