/**
 * Button — shadcn/ui primitive (Radix Slot + class-variance-authority).
 *
 * Generated by the shadcn/ui CLI in upstream projects; we ship the
 * canonical source here so we don't depend on the CLI at build time.
 *
 * Docs: https://ui.shadcn.com/docs/components/button
 */
/* eslint-disable react-refresh/only-export-components -- shadcn primitive pattern: variants are exported alongside the component */
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@/lib/utils";

// Boxy button (components-core.md): square, 1px border, 80ms linear color
// transitions, one primary per view. Heights follow the density tokens
// (compact in the dashboard: sm 24 / md 32 / lg 40). Disabled uses the
// sunken surface + faint ink, never reduced opacity.
const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap border text-sm font-medium leading-none transition-[background-color,border-color,color] duration-75 ease-linear disabled:cursor-not-allowed disabled:border-line-subtle disabled:bg-surface-sunken disabled:text-ink-faint [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        default:
          "border-primary bg-primary text-primary-foreground hover:border-primary-hover hover:bg-primary-hover active:bg-primary-active",
        destructive:
          "border-destructive bg-destructive text-destructive-foreground hover:border-destructive-hover hover:bg-destructive-hover",
        outline:
          "border-line bg-surface text-ink hover:border-line-strong hover:bg-surface-hover active:bg-surface-active",
        secondary:
          "border-line bg-surface-sunken text-ink hover:border-line-strong hover:bg-surface-hover active:bg-surface-active",
        ghost:
          "border-transparent bg-transparent text-ink-muted hover:bg-surface-hover hover:text-ink active:bg-surface-active",
        link: "h-auto border-transparent px-0 text-ink-accent underline-offset-4 hover:underline",
      },
      size: {
        default: "h-[var(--bx-control-md)] px-[var(--bx-pad-x-md)]",
        sm: "h-[var(--bx-control-sm)] px-[var(--bx-pad-x-sm)] text-xs",
        lg: "h-[var(--bx-control-lg)] px-[var(--bx-pad-x-lg)]",
        icon: "h-[var(--bx-control-md)] w-[var(--bx-control-md)] px-0",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return (
      <Comp ref={ref} className={cn(buttonVariants({ variant, size }), className)} {...props} />
    );
  },
);
Button.displayName = "Button";

export { Button, buttonVariants };
