#!/bin/bash

conventional_regex='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9\-]+\))?: .{1,}$|(Merge (.*\s*)*)'

commit_message=$(cat "$1")

if [[ ! $commit_message =~ $conventional_regex ]]; then
  echo "❌ Commit message does not follow Conventional Commits specification."
  echo "Examples of valid commit messages:"
  echo "  feat: add new feature"
  echo "  fix: resolve issue with API"
  echo "  docs: update README"
  echo "  chore: update dependencies"
  echo "Please follow the format: <type>(<scope>): <description>"
  echo "Learn more: https://www.conventionalcommits.org/"
  exit 1
fi
