-- 0036_billing_usage_receipts: the metering usage_events stream + the
-- receipts table (WS-17). Separate from 0035 because (a) the prices +
-- ledger tables are operationally sensitive (billing money) and worth a
-- clean rollback target, and (b) usage_events has very different retention
-- characteristics — it grows fast and is pruned by a River job.
--
-- usage_events is the raw metering stream: one row per (tenant, user,
-- resource, minute) for resources the user consumed during that minute.
-- The metering collector (billing/meter.go) writes these; the rollup job
-- aggregates them into hourly buckets and the ledger post job turns each
-- bucket into a debit ledger_entries row.
--
-- receipts is the per-user-per-period summary, generated by the receipt
-- job from the ledger. Each row carries the total charged for the period
-- + a PDF blob (stored in-row for MVP simplicity; a future WS can move it
-- to SeaweedFS).

CREATE TABLE usage_events (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID        NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    user_id         UUID        NOT NULL REFERENCES users (id)   ON DELETE NO ACTION,
    -- The metering resource key. Matches prices.resource_type so the
    -- rollup job can join the two for the price lookup.
    resource_type   TEXT        NOT NULL,
    -- Integer quantity in the unit (cores, bytes, count, ...). Always
    -- positive; the metering collector enforces non-negativity.
    qty             BIGINT      NOT NULL CHECK (qty >= 0),
    -- The unit the qty is in. Matches prices.unit so the rollup job can
    -- join the two for the price lookup.
    unit            TEXT        NOT NULL,
    -- The minute the usage was recorded for. The metering collector
    -- aligns this to the wall-clock minute; started_at <= ended_at.
    started_at      TIMESTAMPTZ NOT NULL,
    ended_at        TIMESTAMPTZ NOT NULL,
    -- The idempotency key (per (tenant, user, resource, started_at)).
    -- The unique index below makes a duplicate insert fail rather than
    -- double-count.
    idempotency_key TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Hot lookups: per-tenant + per-user scans, rollup queries, dedup.
CREATE INDEX        idx_usage_tenant_id        ON usage_events (tenant_id);
CREATE INDEX        idx_usage_user_id          ON usage_events (tenant_id, user_id, started_at DESC);
CREATE INDEX        idx_usage_resource         ON usage_events (tenant_id, resource_type, started_at DESC);
CREATE UNIQUE INDEX uq_usage_idempotency_key   ON usage_events (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

COMMENT ON TABLE  usage_events                 IS 'Raw metering stream (WS-17). One row per (tenant, user, resource, minute).';
COMMENT ON COLUMN usage_events.resource_type   IS 'Metering resource key (compute.cpu, storage.size, ...). Matches prices.resource_type.';
COMMENT ON COLUMN usage_events.qty             IS 'Integer quantity; always positive. Sign is implicit in the resource semantics.';
COMMENT ON COLUMN usage_events.unit            IS 'Unit the qty is in. Matches prices.unit so the rollup can join.';
COMMENT ON COLUMN usage_events.started_at      IS 'Inclusive start of the metering minute.';
COMMENT ON COLUMN usage_events.ended_at        IS 'Exclusive end of the metering minute.';
COMMENT ON COLUMN usage_events.idempotency_key IS 'Idempotency key for the metering collector; NULL for back-fill rows.';

-- ===========================================================================
-- receipts: per-user-per-period billing summary. One row per (tenant, user,
-- period_start, period_end). The receipt job generates these from the
-- ledger; the user can download the PDF via /api/v1/me/receipts/{id}.pdf.
-- ===========================================================================

CREATE TABLE receipts (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID        NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    user_id         UUID        NOT NULL REFERENCES users (id)   ON DELETE NO ACTION,
    -- Period covered by this receipt. Inclusive on both ends so a monthly
    -- receipt for July 2026 is (period_start=2026-07-01T00:00:00Z,
    -- period_end=2026-07-31T23:59:59.999999Z).
    period_start    TIMESTAMPTZ NOT NULL,
    period_end      TIMESTAMPTZ NOT NULL,
    -- Total charged over the period, in integer centimals. Pre-computed
    -- at generation time so the listing API does not need to re-sum.
    total_cents     BIGINT      NOT NULL,
    currency        TEXT        NOT NULL DEFAULT 'USD',
    -- Generated PDF body. Stored in-row for MVP simplicity; a future WS
    -- can move it to SeaweedFS and replace this column with a key.
    pdf_bytes       BYTEA       NOT NULL DEFAULT ''::bytea,
    -- Generation status. "pending" while the receipt job is building;
    -- "ready" once the PDF is attached. Failed generations stay pending
    -- (the next run overwrites them) — receipts are derived, so we never
    -- need a "failed" terminal state.
    status          TEXT        NOT NULL DEFAULT 'ready',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Hot lookups: list-by-user, lookup-by-id (tenant-scoped), uniqueness
-- guarantees at most one receipt per (tenant, user, period_start).
CREATE INDEX        idx_receipts_user_id       ON receipts (tenant_id, user_id, period_start DESC);
CREATE INDEX        idx_receipts_status        ON receipts (tenant_id, status);
CREATE UNIQUE INDEX uq_receipts_user_period    ON receipts (tenant_id, user_id, period_start)
    WHERE status = 'ready';

COMMENT ON TABLE  receipts              IS 'Per-user-per-period billing summary (WS-17). Generated by the receipt job from the ledger.';
COMMENT ON COLUMN receipts.period_start IS 'Inclusive period start. Monthly cadence by default per WS-17 Open Questions.';
COMMENT ON COLUMN receipts.period_end   IS 'Inclusive period end. Equal to period_start of the next receipt minus 1 second.';
COMMENT ON COLUMN receipts.total_cents  IS 'Total charged over the period in integer centimals; pre-computed at generation time.';
COMMENT ON COLUMN receipts.pdf_bytes    IS 'Generated PDF body. Stored in-row for MVP; future WS may move to SeaweedFS.';
COMMENT ON COLUMN receipts.status       IS 'ready when the PDF is attached. pending while the job is generating.';
