// Package api: router.go registers the OpenAPI-derived routes onto a Fiber app,
// with the path-aware audit gate (per-route RequirePerm) layered on top.
//
// All public routes are defined in api/openapi.yaml and code-generated by
// oapi-codegen into apigen.RegisterHandlers. This file is the single wiring
// point: program/ builds a *Server (api.NewServer) + a PolicyResolver and
// passes them to RegisterRoutes after the middleware stack is in place.
//
// Per-route permission enforcement for the audit endpoints is provided by
// AuditGate — a path-aware middleware that runs RequirePerm for /api/v1/audit*
// paths only. apigen.RegisterHandlers does not natively support per-route
// middleware for Fiber (its FiberServerOptions.Middlewares is global), so the
// gate pattern is the cleanest path that does not require duplicating
// apigen's generated routing table by hand.
package api

import (
	"strings"

	"github.com/avestura/lahijan/api/gen/go"
	"github.com/avestura/lahijan/internal/app/lahijan/api/middleware"
	"github.com/avestura/lahijan/internal/app/lahijan/auth/rbac"
	"github.com/gofiber/fiber/v2"
)

// RegisterRoutes wires the given server onto app with the audit gate applied
// to the audit routes. The handlers live in server.go / auth_handlers.go /
// audit_handlers.go; the routing table is generated by oapi-codegen (apigen).
//
// A catch-all fallback at the end guarantees that requests to undefined paths
// return the standard error envelope (404 not_found) rather than Fiber's
// default plain-text body.
func RegisterRoutes(app *fiber.App, server *Server, policy middleware.PolicyResolver) {
	opts := apigen.FiberServerOptions{}
	if policy != nil {
		opts.Middlewares = []apigen.MiddlewareFunc{AuditGate(policy)}
	}
	apigen.RegisterHandlersWithOptions(app, server, opts)
	// Catch-all: only fires when no registered route matched.
	app.Use(NotFound)
}

// AuditGate returns a path-aware middleware that runs RequirePerm for the
// audit endpoints and bypasses every other path. It exists because:
//
//   - apigen.FiberServerOptions.Middlewares is a flat list (no per-route map),
//     so any middleware we add runs for every route.
//   - Registering audit routes manually would conflict with apigen's
//     registration (Fiber panics on duplicate routes).
//
// The gate inspects c.Path() and dispatches to the right RequirePerm slug:
//
//	/api/v1/audit/export           -> audit.export
//	/api/v1/audit/{id}             -> audit.read
//	/api/v1/audit                  -> audit.read
//	/api/v1/admin/jobs/*/retry     -> platform.jobs.retry
//	/api/v1/admin/jobs/*/cancel    -> platform.jobs.cancel
//	/api/v1/admin/jobs/{id}        -> platform.jobs.read
//	/api/v1/admin/jobs             -> platform.jobs.read
//	/api/v1/admin/plugins/upload   -> plugins.install
//	/api/v1/admin/plugins/*/enable  -> plugins.install
//	/api/v1/admin/plugins/*/disable -> plugins.install
//	/api/v1/admin/plugins/*/permissions/*/* -> plugins.permission.approve
//	/api/v1/admin/plugins/{id}     -> plugins.read  (GET) / plugins.uninstall (DELETE)
//	/api/v1/admin/plugins          -> plugins.read
//
// Everything else: c.Next() (no enforcement; routes that need it must add
// their own per-route RequirePerm or be gated through this same function as
// the privileged surface grows).
func AuditGate(policy middleware.PolicyResolver) apigen.MiddlewareFunc {
	return func(c *fiber.Ctx) error {
		path := c.Path()
		switch {
		// WS-08: audit log endpoints.
		case path == "/api/v1/audit/export":
			return middleware.RequirePerm(policy, rbac.PermAuditExport)(c)
		case path == "/api/v1/audit":
			return middleware.RequirePerm(policy, rbac.PermAuditRead)(c)
		case strings.HasPrefix(path, "/api/v1/audit/"):
			return middleware.RequirePerm(policy, rbac.PermAuditRead)(c)

		// WS-09: admin job system endpoints. These are platform-only; only
		// the platform.admin role (auto-bypass in the evaluator) holds the
		// platform.jobs.* permissions, so tenant-scoped admins cannot reach
		// another tenant's jobs.
		case strings.HasPrefix(path, "/api/v1/admin/jobs/") && strings.HasSuffix(path, "/retry"):
			return middleware.RequirePerm(policy, rbac.PermPlatformJobsRetry)(c)
		case strings.HasPrefix(path, "/api/v1/admin/jobs/") && strings.HasSuffix(path, "/cancel"):
			return middleware.RequirePerm(policy, rbac.PermPlatformJobsCancel)(c)
		case path == "/api/v1/admin/jobs":
			return middleware.RequirePerm(policy, rbac.PermPlatformJobsRead)(c)
		case strings.HasPrefix(path, "/api/v1/admin/jobs/"):
			return middleware.RequirePerm(policy, rbac.PermPlatformJobsRead)(c)

		// WS-10a: admin plugin endpoints. The WS-10a DoD requires "only
		// platform.admin can hit the admin plugin API". Concretely this
		// means every /admin/plugins/* path MUST require plugins.install
		// (or plugins.uninstall / plugins.permission.approve) — those
		// slugs are NOT in the tenant.member / tenant.viewer bundles, so
		// only tenant.admin and platform.admin reach the handlers. The
		// tenant-scoped plugins.read permission (which viewer+member hold)
		// is reserved for a future /api/v1/plugins tenant-scoped surface
		// (WS-21); the admin API is separate.
		case path == "/api/v1/admin/plugins/upload" && c.Method() == "POST":
			return middleware.RequirePerm(policy, rbac.PermPluginsInstall)(c)
		case strings.HasPrefix(path, "/api/v1/admin/plugins/") && strings.HasSuffix(path, "/enable"):
			return middleware.RequirePerm(policy, rbac.PermPluginsInstall)(c)
		case strings.HasPrefix(path, "/api/v1/admin/plugins/") && strings.HasSuffix(path, "/disable"):
			return middleware.RequirePerm(policy, rbac.PermPluginsInstall)(c)
		case strings.HasPrefix(path, "/api/v1/admin/plugins/") && strings.Contains(path, "/permissions/"):
			return middleware.RequirePerm(policy, rbac.PermPluginsPermissionApprove)(c)
		case strings.HasPrefix(path, "/api/v1/admin/plugins/") && c.Method() == "DELETE":
			return middleware.RequirePerm(policy, rbac.PermPluginsUninstall)(c)
		case path == "/api/v1/admin/plugins":
			return middleware.RequirePerm(policy, rbac.PermPluginsInstall)(c)
		case strings.HasPrefix(path, "/api/v1/admin/plugins/"):
			return middleware.RequirePerm(policy, rbac.PermPluginsInstall)(c)
		}
		return c.Next()
	}
}
