// Package api: router.go registers the OpenAPI-derived routes onto a Fiber app,
// with the path-aware audit gate (per-route RequirePerm) layered on top.
//
// All public routes are defined in api/openapi.yaml and code-generated by
// oapi-codegen into apigen.RegisterHandlers. This file is the single wiring
// point: program/ builds a *Server (api.NewServer) + a PolicyResolver and
// passes them to RegisterRoutes after the middleware stack is in place.
//
// Per-route permission enforcement for the audit endpoints is provided by
// AuditGate — a path-aware middleware that runs RequirePerm for /api/v1/audit*
// paths only. apigen.RegisterHandlers does not natively support per-route
// middleware for Fiber (its FiberServerOptions.Middlewares is global), so the
// gate pattern is the cleanest path that does not require duplicating
// apigen's generated routing table by hand.
package api

import (
	"strings"

	"github.com/avestura/lahijan/api/gen/go"
	"github.com/avestura/lahijan/internal/app/lahijan/api/middleware"
	"github.com/avestura/lahijan/internal/app/lahijan/auth/rbac"
	"github.com/gofiber/fiber/v2"
)

// RegisterRoutes wires the given server onto app with the audit gate applied
// to the audit routes. The handlers live in server.go / auth_handlers.go /
// audit_handlers.go; the routing table is generated by oapi-codegen (apigen).
//
// A catch-all fallback at the end guarantees that requests to undefined paths
// return the standard error envelope (404 not_found) rather than Fiber's
// default plain-text body.
func RegisterRoutes(app *fiber.App, server *Server, policy middleware.PolicyResolver) {
	opts := apigen.FiberServerOptions{}
	if policy != nil {
		opts.Middlewares = []apigen.MiddlewareFunc{AuditGate(policy)}
	}
	apigen.RegisterHandlersWithOptions(app, server, opts)
	// Catch-all: only fires when no registered route matched.
	app.Use(NotFound)
}

// AuditGate returns a path-aware middleware that runs RequirePerm for the
// privileged endpoints and bypasses every other path. It exists because:
//
//   - apigen.FiberServerOptions.Middlewares is a flat list (no per-route map),
//     so any middleware we add runs for every route.
//   - Registering routes manually would conflict with apigen's
//     registration (Fiber panics on duplicate routes).
//
// The gate inspects c.Path() + c.Method() and dispatches to the right
// RequirePerm slug:
//
//	/api/v1/audit/export           -> audit.export
//	/api/v1/audit/{id}             -> audit.read
//	/api/v1/audit                  -> audit.read
//	/api/v1/admin/jobs/*/retry     -> platform.jobs.retry
//	/api/v1/admin/jobs/*/cancel    -> platform.jobs.cancel
//	/api/v1/admin/jobs/{id}        -> platform.jobs.read
//	/api/v1/admin/jobs             -> platform.jobs.read
//	/api/v1/admin/plugins/upload   -> plugins.install
//	/api/v1/admin/plugins/*/enable  -> plugins.install
//	/api/v1/admin/plugins/*/disable -> plugins.install
//	/api/v1/admin/plugins/*/permissions/*/* -> plugins.permission.approve
//	/api/v1/admin/plugins/install/*  -> plugins.install     (WS-10c marketplace)
//	/api/v1/admin/plugins/upgrade/*  -> plugins.install     (WS-10c marketplace)
//	/api/v1/admin/marketplace        -> plugins.read        (WS-10c marketplace)
//	/api/v1/admin/marketplace/*      -> plugins.read        (WS-10c marketplace)
//	/api/v1/admin/plugins/{id}     -> plugins.read  (GET) / plugins.uninstall (DELETE)
//	/api/v1/admin/plugins          -> plugins.read
//	/api/v1/compute/instances POST                    -> compute.instance.create
//	/api/v1/compute/instances GET                     -> compute.instance.read
//	/api/v1/compute/instances/{id} GET / PATCH        -> compute.instance.read / .update
//	/api/v1/compute/instances/{id} DELETE             -> compute.instance.delete
//	/api/v1/compute/instances/{id}/{start|stop|...}   -> compute.instance.<action>
//	/api/v1/compute/instances/{id}/exec POST          -> compute.instance.start
//	                                                          (exec needs a running instance)
//	/api/v1/compute/images GET                        -> compute.image.read
//	/api/v1/compute/images POST                       -> compute.instance.create
//	                                                          (custom upload is create-adjacent)
//	/api/v1/compute/images/{id} GET                   -> compute.image.read
//	/api/v1/compute/images/{id} DELETE                -> compute.instance.delete
//	/api/v1/compute/profiles GET / POST               -> compute.profile.read / .apply
//	/api/v1/compute/profiles/{id} GET                 -> compute.profile.read
//	/api/v1/compute/profiles/{id} DELETE              -> compute.profile.apply
//	/api/v1/compute/networks GET / POST               -> compute.network.read / .create
//	/api/v1/compute/networks/{id} GET                 -> compute.network.read
//	/api/v1/compute/networks/{id} DELETE              -> compute.network.create
//	/api/v1/compute/storage GET / POST                -> compute.storage_pool.read
//	/api/v1/compute/storage/{id} GET                  -> compute.storage_pool.read
//	/api/v1/compute/storage/{id} DELETE               -> compute.storage_pool.read
//
// Everything else: c.Next() (no enforcement; routes that need it must add
// their own per-route RequirePerm or be gated through this same function as
// the privileged surface grows).
func AuditGate(policy middleware.PolicyResolver) apigen.MiddlewareFunc {
	return func(c *fiber.Ctx) error {
		path := c.Path()
		method := c.Method()
		switch {
		// WS-08: audit log endpoints.
		case path == "/api/v1/audit/export":
			return middleware.RequirePerm(policy, rbac.PermAuditExport)(c)
		case path == "/api/v1/audit":
			return middleware.RequirePerm(policy, rbac.PermAuditRead)(c)
		case strings.HasPrefix(path, "/api/v1/audit/"):
			return middleware.RequirePerm(policy, rbac.PermAuditRead)(c)

		// WS-09: admin job system endpoints. These are platform-only; only
		// the platform.admin role (auto-bypass in the evaluator) holds the
		// platform.jobs.* permissions, so tenant-scoped admins cannot reach
		// another tenant's jobs.
		case strings.HasPrefix(path, "/api/v1/admin/jobs/") && strings.HasSuffix(path, "/retry"):
			return middleware.RequirePerm(policy, rbac.PermPlatformJobsRetry)(c)
		case strings.HasPrefix(path, "/api/v1/admin/jobs/") && strings.HasSuffix(path, "/cancel"):
			return middleware.RequirePerm(policy, rbac.PermPlatformJobsCancel)(c)
		case path == "/api/v1/admin/jobs":
			return middleware.RequirePerm(policy, rbac.PermPlatformJobsRead)(c)
		case strings.HasPrefix(path, "/api/v1/admin/jobs/"):
			return middleware.RequirePerm(policy, rbac.PermPlatformJobsRead)(c)

		// WS-10c: marketplace endpoints. The browse paths (GET
		// /marketplace, GET /marketplace/{name}) require plugins.read
		// so tenant admins can see what's available. The install +
		// upgrade paths require plugins.install because they persist
		// rows + emit audit events.
		case path == "/api/v1/admin/marketplace":
			return middleware.RequirePerm(policy, rbac.PermPluginsRead)(c)
		case strings.HasPrefix(path, "/api/v1/admin/marketplace/"):
			return middleware.RequirePerm(policy, rbac.PermPluginsRead)(c)
		case strings.HasPrefix(path, "/api/v1/admin/plugins/install/"):
			return middleware.RequirePerm(policy, rbac.PermPluginsInstall)(c)
		case strings.HasPrefix(path, "/api/v1/admin/plugins/upgrade/"):
			return middleware.RequirePerm(policy, rbac.PermPluginsInstall)(c)

		// WS-10a: admin plugin endpoints. The WS-10a DoD requires "only
		// platform.admin can hit the admin plugin API". Concretely this
		// means every /admin/plugins/* path MUST require plugins.install
		// (or plugins.uninstall / plugins.permission.approve) — those
		// slugs are NOT in the tenant.member / tenant.viewer bundles, so
		// only tenant.admin and platform.admin reach the handlers. The
		// tenant-scoped plugins.read permission (which viewer+member hold)
		// is reserved for a future /api/v1/plugins tenant-scoped surface
		// (WS-21); the admin API is separate.
		case path == "/api/v1/admin/plugins/upload" && c.Method() == "POST":
			return middleware.RequirePerm(policy, rbac.PermPluginsInstall)(c)
		case strings.HasPrefix(path, "/api/v1/admin/plugins/") && strings.HasSuffix(path, "/enable"):
			return middleware.RequirePerm(policy, rbac.PermPluginsInstall)(c)
		case strings.HasPrefix(path, "/api/v1/admin/plugins/") && strings.HasSuffix(path, "/disable"):
			return middleware.RequirePerm(policy, rbac.PermPluginsInstall)(c)
		case strings.HasPrefix(path, "/api/v1/admin/plugins/") && strings.Contains(path, "/permissions/"):
			return middleware.RequirePerm(policy, rbac.PermPluginsPermissionApprove)(c)
		case strings.HasPrefix(path, "/api/v1/admin/plugins/") && c.Method() == "DELETE":
			return middleware.RequirePerm(policy, rbac.PermPluginsUninstall)(c)
		case path == "/api/v1/admin/plugins":
			return middleware.RequirePerm(policy, rbac.PermPluginsInstall)(c)
		case strings.HasPrefix(path, "/api/v1/admin/plugins/"):
			return middleware.RequirePerm(policy, rbac.PermPluginsInstall)(c)

		// WS-14: compute module endpoints. Every /api/v1/compute/* path
		// is gated; the slug maps 1:1 with the rbac.PermCompute*
		// registry so the policy evaluator can answer with the caller's
		// role grant (tenant.viewer / member / admin / owner).
		case isComputeInstanceExecPath(path) && method == "POST":
			// exec needs a running instance; reuse the start permission
			// since both involve "interact with a running instance".
			return middleware.RequirePerm(policy, rbac.PermComputeInstanceStart)(c)
		case isComputeInstanceLifecyclePath(path) && method == "POST":
			return middleware.RequirePerm(policy, computeInstanceActionPerm(path))(c)
		case isComputeInstancePath(path) && method == "POST":
			return middleware.RequirePerm(policy, rbac.PermComputeInstanceCreate)(c)
		case isComputeInstancePath(path) && method == "GET":
			return middleware.RequirePerm(policy, rbac.PermComputeInstanceRead)(c)
		case isComputeInstancePath(path) && method == "PATCH":
			return middleware.RequirePerm(policy, rbac.PermComputeInstanceUpdate)(c)
		case isComputeInstancePath(path) && method == "DELETE":
			return middleware.RequirePerm(policy, rbac.PermComputeInstanceDelete)(c)
		case isComputeImagePath(path) && method == "POST":
			return middleware.RequirePerm(policy, rbac.PermComputeInstanceCreate)(c)
		case isComputeImagePath(path) && method == "GET":
			return middleware.RequirePerm(policy, rbac.PermComputeImageRead)(c)
		case isComputeImagePath(path) && method == "DELETE":
			return middleware.RequirePerm(policy, rbac.PermComputeInstanceDelete)(c)
		case isComputeProfilePath(path) && method == "POST":
			return middleware.RequirePerm(policy, rbac.PermComputeProfileApply)(c)
		case isComputeProfilePath(path) && method == "GET":
			return middleware.RequirePerm(policy, rbac.PermComputeProfileRead)(c)
		case isComputeProfilePath(path) && method == "DELETE":
			return middleware.RequirePerm(policy, rbac.PermComputeProfileApply)(c)
		case isComputeNetworkPath(path) && method == "POST":
			return middleware.RequirePerm(policy, rbac.PermComputeNetworkCreate)(c)
		case isComputeNetworkPath(path) && method == "GET":
			return middleware.RequirePerm(policy, rbac.PermComputeNetworkRead)(c)
		case isComputeNetworkPath(path) && method == "DELETE":
			return middleware.RequirePerm(policy, rbac.PermComputeNetworkCreate)(c)
		case isComputeStoragePath(path) && method == "POST":
			return middleware.RequirePerm(policy, rbac.PermComputeNetworkCreate)(c)
		case isComputeStoragePath(path) && method == "GET":
			return middleware.RequirePerm(policy, rbac.PermComputeStoragePoolRead)(c)
		case isComputeStoragePath(path) && method == "DELETE":
			return middleware.RequirePerm(policy, rbac.PermComputeStoragePoolRead)(c)
		}
		return c.Next()
	}
}

// isComputeInstancePath reports whether path targets the instances
// collection or a specific instance (but not the action sub-paths).
func isComputeInstancePath(path string) bool {
	if path == "/api/v1/compute/instances" {
		return true
	}
	return strings.HasPrefix(path, "/api/v1/compute/instances/") &&
		!isComputeInstanceLifecyclePath(path) &&
		!isComputeInstanceExecPath(path)
}

// isComputeInstanceLifecyclePath reports whether path is one of the
// /instances/{id}/{action} lifecycle endpoints.
func isComputeInstanceLifecyclePath(path string) bool {
	for _, a := range []string{"start", "stop", "restart", "freeze", "unfreeze"} {
		if strings.HasSuffix(path, "/"+a) && strings.HasPrefix(path, "/api/v1/compute/instances/") {
			return true
		}
	}
	return false
}

// isComputeInstanceExecPath reports whether path is the exec endpoint.
func isComputeInstanceExecPath(path string) bool {
	return strings.HasPrefix(path, "/api/v1/compute/instances/") && strings.HasSuffix(path, "/exec")
}

// computeInstanceActionPerm maps the trailing path segment to the matching
// rbac permission slug. Caller MUST ensure path is a lifecycle path.
func computeInstanceActionPerm(path string) string {
	switch {
	case strings.HasSuffix(path, "/start"):
		return rbac.PermComputeInstanceStart
	case strings.HasSuffix(path, "/stop"):
		return rbac.PermComputeInstanceStop
	case strings.HasSuffix(path, "/restart"):
		return rbac.PermComputeInstanceRestart
	case strings.HasSuffix(path, "/freeze"), strings.HasSuffix(path, "/unfreeze"):
		// freeze/unfreeze are state changes; reuse stop (the closest
		// permission in the registry). A future WS can split these.
		return rbac.PermComputeInstanceStop
	}
	return rbac.PermComputeInstanceRead
}

// isComputeImagePath / isComputeProfilePath / isComputeNetworkPath /
// isComputeStoragePath mirror isComputeInstancePath for the secondary
// resources.
func isComputeImagePath(path string) bool {
	if path == "/api/v1/compute/images" {
		return true
	}
	return strings.HasPrefix(path, "/api/v1/compute/images/")
}

func isComputeProfilePath(path string) bool {
	if path == "/api/v1/compute/profiles" {
		return true
	}
	return strings.HasPrefix(path, "/api/v1/compute/profiles/")
}

func isComputeNetworkPath(path string) bool {
	if path == "/api/v1/compute/networks" {
		return true
	}
	return strings.HasPrefix(path, "/api/v1/compute/networks/")
}

func isComputeStoragePath(path string) bool {
	if path == "/api/v1/compute/storage" {
		return true
	}
	return strings.HasPrefix(path, "/api/v1/compute/storage/")
}
